// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Common
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class FixMatrix3x3Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.FixMatrix3x3>
    {


        public void Serialize(ref MessagePackWriter writer, global::Common.FixMatrix3x3 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(9);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M11, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M12, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M13, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M21, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M22, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M23, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M31, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M32, options);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.M33, options);
        }

        public global::Common.FixMatrix3x3 Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __M11__ = default(global::Common.Fix64);
            var __M12__ = default(global::Common.Fix64);
            var __M13__ = default(global::Common.Fix64);
            var __M21__ = default(global::Common.Fix64);
            var __M22__ = default(global::Common.Fix64);
            var __M23__ = default(global::Common.Fix64);
            var __M31__ = default(global::Common.Fix64);
            var __M32__ = default(global::Common.Fix64);
            var __M33__ = default(global::Common.Fix64);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __M11__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __M12__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __M13__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __M21__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __M22__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __M23__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __M31__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 7:
                        __M32__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 8:
                        __M33__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Common.FixMatrix3x3(__M11__, __M12__, __M13__, __M21__, __M22__, __M23__, __M31__, __M32__, __M33__);
            ____result.M11 = __M11__;
            ____result.M12 = __M12__;
            ____result.M13 = __M13__;
            ____result.M21 = __M21__;
            ____result.M22 = __M22__;
            ____result.M23 = __M23__;
            ____result.M31 = __M31__;
            ____result.M32 = __M32__;
            ____result.M33 = __M33__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
