// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Common
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MouseInputFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.MouseInput>
    {


        public void Serialize(ref MessagePackWriter writer, global::Common.MouseInput value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Serialize(ref writer, value.MouseButtons, options);
            formatterResolver.GetFormatterWithVerify<global::Common.FixVector2>().Serialize(ref writer, value.ScrollDelta, options);
            formatterResolver.GetFormatterWithVerify<global::Common.FixVector2>().Serialize(ref writer, value.Delta, options);
            formatterResolver.GetFormatterWithVerify<global::Common.FixVector3>().Serialize(ref writer, value.Position, options);
        }

        public global::Common.MouseInput Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __MouseButtons__ = default(global::System.Collections.Generic.List<int>);
            var __ScrollDelta__ = default(global::Common.FixVector2);
            var __Delta__ = default(global::Common.FixVector2);
            var __Position__ = default(global::Common.FixVector3);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __MouseButtons__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __ScrollDelta__ = formatterResolver.GetFormatterWithVerify<global::Common.FixVector2>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Delta__ = formatterResolver.GetFormatterWithVerify<global::Common.FixVector2>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __Position__ = formatterResolver.GetFormatterWithVerify<global::Common.FixVector3>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Common.MouseInput();
            ____result.MouseButtons = __MouseButtons__;
            ____result.ScrollDelta = __ScrollDelta__;
            ____result.Delta = __Delta__;
            ____result.Position = __Position__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
