// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;
    using System.Buffers;
    using MessagePack;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(13)
            {
                { typeof(global::System.Collections.Generic.List<int>), 0 },
                { typeof(byte[][]), 1 },
                { typeof(global::Common.UserInputs[]), 2 },
                { typeof(global::Common.IInput), 3 },
                { typeof(global::Common.Fix64), 4 },
                { typeof(global::Common.FixQuaternion), 5 },
                { typeof(global::Common.FixVector2), 6 },
                { typeof(global::Common.FixVector3), 7 },
                { typeof(global::Common.AxisInput), 8 },
                { typeof(global::Common.KeyInput), 9 },
                { typeof(global::Common.UserInputs), 10 },
                { typeof(global::Common.LockstepInputs), 11 },
                { typeof(global::Common.MouseInput), 12 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<int>();
                case 1: return new global::MessagePack.Formatters.ArrayFormatter<byte[]>();
                case 2: return new global::MessagePack.Formatters.ArrayFormatter<global::Common.UserInputs>();
                case 3: return new MessagePack.Formatters.Common.IInputFormatter();
                case 4: return new MessagePack.Formatters.Common.Fix64Formatter();
                case 5: return new MessagePack.Formatters.Common.FixQuaternionFormatter();
                case 6: return new MessagePack.Formatters.Common.FixVector2Formatter();
                case 7: return new MessagePack.Formatters.Common.FixVector3Formatter();
                case 8: return new MessagePack.Formatters.Common.AxisInputFormatter();
                case 9: return new MessagePack.Formatters.Common.KeyInputFormatter();
                case 10: return new MessagePack.Formatters.Common.UserInputsFormatter();
                case 11: return new MessagePack.Formatters.Common.LockstepInputsFormatter();
                case 12: return new MessagePack.Formatters.Common.MouseInputFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name
