// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Common
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class LockstepInputsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Common.LockstepInputs>
    {


        public void Serialize(ref MessagePackWriter writer, global::Common.LockstepInputs value, global::MessagePack.MessagePackSerializerOptions options)
        {
            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.TickId);
            formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Serialize(ref writer, value.DeltaTime, options);
            formatterResolver.GetFormatterWithVerify<global::Common.UserInputs[][]>().Serialize(ref writer, value.UserInputs, options);
        }

        public global::Common.LockstepInputs Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __TickId__ = default(int);
            var __DeltaTime__ = default(global::Common.Fix64);
            var __UserInputs__ = default(global::Common.UserInputs[][]);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __TickId__ = reader.ReadInt32();
                        break;
                    case 1:
                        __DeltaTime__ = formatterResolver.GetFormatterWithVerify<global::Common.Fix64>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __UserInputs__ = formatterResolver.GetFormatterWithVerify<global::Common.UserInputs[][]>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Common.LockstepInputs();
            ____result.TickId = __TickId__;
            ____result.DeltaTime = __DeltaTime__;
            ____result.UserInputs = __UserInputs__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
